databases:
  - name: soberana-db
    plan: free
    databaseName: soberana_db
    user: soberana_user

services:
  - type: web
    name: soberana-api
    runtime: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: Host=dpg-d81td777f7vs73efue6g-a;Database=soberana_db;Username=soberana_user;Password=E2ysLo26epYUfw2qQgrBSd75YhzZxRgT;SSL Mode=Disable;Trust Server Certificate=true

  - type: web
    name: soberana-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build -- --configuration production
    staticPublishPath: dist/frontend/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
